### ISSUE TITLE
COMException 0x8001010E thrown in PrepareContextMenuWindow

### ISSUE THREAD

**Issue by ChristianGalla** [HavenDV/H.NotifyIcon#186]
### Describe the bug

Hi,

nice project!

After updating my app [AutoStartConfirm](https://github.com/ChristianGalla/AutoStartConfirm/tree/update-dependencies) from .NET 8 to 9 and H.NotifyIcon.WinUI from 2.0.124 to 2.2.0, creating a new [TaskbarIcon instance](https://github.com/ChristianGalla/AutoStartConfirm/blob/11f8e1b26bce67d5ae770431034995e8bc329400/AutoStartConfirm/App.xaml.cs#L244) throws the following error:

```
System.Runtime.InteropServices.COMException
  HResult=0x8001010E
  Message=
  Source=WinRT.Runtime
  StackTrace:
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|38_0(Int32 hr) in WinRT\ExceptionHelpers.cs:line 134
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr) in WinRT\ExceptionHelpers.cs:line 122
   at ABI.Microsoft.UI.Xaml.IWindowMethods.get_Content(IObjectReference _obj)
   at Microsoft.UI.Xaml.Window.get_Content()
   at H.NotifyIcon.TaskbarIcon.<>c__DisplayClass25_0.<<PrepareContextMenuWindow>b__1>d.MoveNext()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

While debugging I had a look at the failing [code of this library]( https://github.com/HavenDV/H.NotifyIcon/blob/fd2185ed1cf807428666508da83abbe66040aac4/src/libs/H.NotifyIcon.Shared/TaskbarIcon.ContextMenu.WinUI.SecondWindow.cs#L111) and I noticed the following:
There is a line to delay code execution for 1 ms. Before this line window.Content is set, after the wait trying to access window.Content throws the mentioned exception.

```C#
await Task.Delay(1).ConfigureAwait(true);
flyout.ShowAt(window.Content, new FlyoutShowOptions
{
    ShowMode = FlyoutShowMode.Transient,
});
```

There is no error message, but 0x8001010E usually means RPC_E_WRONG_THREAD. According to the Visual Studio thread window between these lines the executing thread switches from main to another Worker Thread ".NET TP Worker". Because access of GUI elements is only possible in the main thread, execution fails.

According to the documentation [ConfigureAwait](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.configureawait?view=net-9.0#system-threading-tasks-task-configureawait(system-boolean)) not guarantees continuation in the calling thread.

Maybe the await is a hack for previous versions that is not needed anymore and can be removed? If it is still needed, switching to something like Dispatcher.Invoke may be needed.

### Expected behavior

No error is thrown

### NuGet package version

Microsoft.WindowsAppSDK 1.6.241114003
H.NotifyIcon.WinUI 2.2.0

### Platform

WinUI

### IDE

Visual Studio 2022

### Windows Version

Windows 10

### WindowsAppSDK Version

Other

### WindowsAppSDK Type

Unpackaged

### Additional context

Maybe this is related to issue https://github.com/HavenDV/H.NotifyIcon/issues/175?

**Comment by ChristianGalla** [comment]
I was able to reproduce this issue on .NET 8 on every NotifyIcon 2.1 and 2.2 version.
2.0.131 is running fine.
